---
title: "Many models"
description: |
  A short description of the post.
author:
  - name: Thinh Tran
    url: {}
date: 10-25-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(tidyverse)
```

```{r}
key_crop_yields <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-01/key_crop_yields.csv")
land_use <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-01/land_use_vs_yield_change_in_cereal_production.csv")
```


```{r}
top_countries <- land_use %>% 
  janitor::clean_names() %>% 
  filter(!is.na(code), entity != 'World') %>% 
  group_by(entity) %>% 
  filter(year == max(year)) %>% 
  ungroup() %>% 
  slice_max(total_population_gapminder, n = 30) %>% 
  pull(entity)
```

```{r}
tidy_yields <- key_crop_yields %>% 
  janitor::clean_names() %>% 
  pivot_longer(wheat_tonnes_per_hectare:bananas_tonnes_per_hectare,
               names_to = "crop", values_to = "yield"
  ) %>%
  mutate(crop = str_remove(crop, "_tonnes_per_hectare")) %>% 
  filter(
    crop %in% c("wheat", "rice", "maize", "barley"),
    entity %in% top_countries,
    !is.na(yield)
  )
```



```{r}
tidy_yields %>% 
  ggplot(aes(year, yield, color = crop)) +
  geom_line(alpha = .7, size = 1.5) + 
  geom_point() + 
  facet_wrap(~ entity, ncol = 5) + 
  scale_x_continuous(guide = guide_axis(angle = 90)) + 
  labs(x = NULL, y = "yield (tons per hectare")
```

# Modelling 

```{r}
library(tidymodels)
tidy_lm <- tidy_yields %>% 
  nest(yields = c(year, yield)) %>% 
  mutate(model = map(yields, ~ lm(yield ~ year, data = .x)))

slopes <- tidy_lm %>% 
  mutate(coefs = map(model, tidy)) %>% 
  unnest(coefs) %>% 
  filter(term == "year") %>% 
  mutate(p.value = p.adjust(p.value))
  
slopes
```

# Explore the results 

```{r}
library(ggrepel)
slopes %>% 
  ggplot(aes(estimate, p.value, label = entity)) + 
  geom_vline(
    xintercept = 0, lty = 2, 
    size = 1.5, alpha = 0.7, color = "gray50"
  ) + 
  geom_point(aes(color = crop), alpha = 0.8, size = 2.5, show.legend = FALSE) + 
  scale_y_log10() + 
  facet_wrap(~ crop) + 
  geom_text_repel(size = 3)
```

