---
title: "Untitled"
author: "Thinh"
date: "9/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
theme_set(theme_light())
```

```{r}
stack_overflow <- read_csv("https://raw.githubusercontent.com/juliasilge/supervised-ML-case-studies-course/master/data/stack_overflow.csv") %>% 
  mutate(remote = factor(remote, levels = c("Remote", "Not remote"))) %>% 
  mutate(across(is.character, factor))
```

```{r}
head(stack_overflow)

stack_overflow %>% 
  glimpse()

stack_overflow %>% 
  count(remote, sort = TRUE)

stack_overflow %>% 
  count(country, sort= TRUE)

stack_overflow %>% 
  count(years_coded_job, sort = TRUE)
```


```{r}
stack_overflow %>% 
  ggplot(aes(remote, years_coded_job)) + 
  geom_boxplot() +
  labs(
    x = "",
    y = "Years of professional coding experience"
  )
```

### Models with imbalanced dataset
There are about ten times more non-remote developers than there are remote developers
```{r}
# load tidymodels 
library(tidymodels)

# create stack_select dataset 
stack_select <- stack_overflow %>% 
  select(-respondent)

# split data into training and testing tests
set.seed(1234)
stack_split <- stack_select %>% 
  initial_split(p = 0.8, 
                stata = remote)

stack_train <- training(stack_split)
stack_test <- testing(stack_split)

```


```{r}
stack_recipe <- recipe(remote ~ ., data = stack_train) %>% 
  step_downsample(remote)

stack_prep <- prep(stack_recipe)
stack_down <- juice(stack_prep)

stack_down %>% 
  count(remote)
```

### Predicting remote status

```{r}
glm_spec <- parsnip::logistic_reg() %>% 
  set_engine("glm")

tree_spec <- parsnip::decision_tree() %>% 
  set_engine("rpart") %>% 
  set_mode("classification")
```

```{r}
# build a workflow

stack_wf <- workflow() %>% 
  add_recipe(stack_recipe) 

stack_glm <- stack_wf %>% 
  add_model(glm_spec) %>% 
  fit(data = stack_train)

stack_tree <- stack_wf %>% 
  add_model(tree_spec) %>% 
  fit(data = stack_train)
```

```{r}
results <- stack_test %>%
    bind_cols(predict(stack_glm, stack_test) %>%
                  rename(.pred_glm = .pred_class)) %>%
    bind_cols(predict(stack_tree, stack_test) %>%
                  rename(.pred_tree = .pred_class))

results %>%
    conf_mat(truth = remote, estimate = .pred_glm)

results %>%
    conf_mat(truth = remote, estimate = .pred_tree)

## Calculate accuracy
accuracy(results, truth = remote, estimate = .pred_glm)
accuracy(results, truth = remote, estimate = .pred_tree)

## Calculate positive predict value
ppv(results, truth = remote, estimate = .pred_glm)
ppv(results, truth = remote, estimate = .pred_tree)
```

